### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jennifer Sturgill",
  "email": "jenn@example.com",
  "password": "password1",
  "password_confirmation": "password1"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "phil@example.com",
  "password": "password"
}
